### ISSUE TITLE
Question: Possible to export to VRM with materials/shaders?

### ISSUE THREAD

**Issue by Enby-Axolotl** [saturday06/VRM-Addon-for-Blender#107]
I absolutely love this addon for blender and have had so much fun practicing making my own VTUBERs from scratch with it! This addon single-handedly got me back into 3D modelling! I just don't know if it's possible to get the shaders to export with the model (I tried making a toon shader from scratch and it ended up just making the model white- very sad.) If it's not currently available, is there a way you could add it to the future? If not that's fine! Thank you for your time! :D

**Comment by saturday06** [comment]
Hi!

The add-on exports materials in the same way as the Blender glTF 2.0 Add-on because VRM is derived from glTF 2.0. glTF 2.0 Add-on is limited in the number of supported shader node groups, see documentation.
https://docs.blender.org/manual/en/3.0/addons/import_export/scene_gltf2.html?highlight=gltf#exported-materials

In addition, our add-on adds VRM's own shader node group. Materials are exported using them.
![](https://user-images.githubusercontent.com/532872/159160104-c7c26e97-8edc-4726-ab9a-a1fda4dbce9b.png)

See also:
https://github.com/saturday06/VRM_Addon_for_Blender/issues/99

**Comment by Enby-Axolotl** [comment]
Ah! Thank you oh so much for your help! I hope you have a fantastic day!!!

**Comment by saturday06** [comment]
Material documentation is ready.

- https://vrm-addon-for-blender.info/en/material-pbr?locale_redirection
- https://vrm-addon-for-blender.info/en/material-mtoon?locale_redirection
