### ISSUE TITLE
Bug report: Normals exporting/importing incorrectly

### ISSUE THREAD

**Issue by violetgynoid** [saturday06/VRM-Addon-for-Blender#222]
## Describe the bug

Normal maps appear to be incorrect after exporting with a texture, despite the normal maps being correct before export. When I re-import a model that has been exported through the addon with a material applied, the normals appear correct despite the texture displaying improperly in both Blender and other programs that use VRM models, but when I re-calculate them, they are wildly incorrect and appear to have inside and outside faces placed at random. 

## To Reproduce

1. Export model
2. Re-import model
3. Recalculate normals (Alt-N) 

## Expected behavior

The expected behavior is that it exports looking similarly to how it does in the viewport with the correct normal mapping.

## Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/29111040/224781276-cbe37f81-bfef-4d7a-9242-8aa6594b7322.png)

How the model looks in the viewport, pre-export.

![Screenshot_3](https://user-images.githubusercontent.com/29111040/224781479-892dcb8d-49a2-46ad-9bd3-cc6608a9e63d.png)

The correct normals for the model.

![Screenshot_5](https://user-images.githubusercontent.com/29111040/224781547-5b8bb720-aee8-44a9-bed1-55c2ad8a5c54.png)

How the model looks in the viewport after importing the exported file.

![Screenshot_4](https://user-images.githubusercontent.com/29111040/224781597-b142b3ee-1645-4695-b69c-6a8f969fd8a4.png)

The incorrect recalculated normals for the model.

## Desktop

- OS: Windows 10
- Blender 3.2.0
- Addon Version 2.15.0

## Additional context

This issue may be brought on by my usage of many complicated meshes instead of a single humanoid body mesh, as the main mesh I'm having issues with is a very complex mask as opposed to a simpler cube or lower-poly object that I could repair by hand. It may also be related to my usage of SimpleBake, but I am unsure how that would cause this issue.

**Comment by violetgynoid** [comment]
![image](https://user-images.githubusercontent.com/29111040/224784695-efbdb37b-78b8-4c0a-b5ba-40f403608d90.png)

After a quick test, it appears that this behavior occurs with simple meshes as well, not just the complicated ones.

**Comment by saturday06** [comment]
Please execute "Mesh >> Merge >> By distance" before "Recalculate normals".

<img width="312" alt="" src="https://user-images.githubusercontent.com/532872/224990411-742510ca-7ea1-4d5f-8645-9d2dc50e6503.png">

Normal recalculation requires adjacent faces to share vertices. However, my understanding is that glTF may not do so.

Or if I am wrong please create an issue in the offitial glTF exporter https://github.com/KhronosGroup/glTF-Blender-IO because the VRM 1.0 export process is implemented using the official glTF exporter and the VRM 0.0 export process will be too. The VRM format is defined using extensions to glTF, and glTF is used as is, especially for meshes and normals.

**Comment by violetgynoid** [comment]
The same behavior occurs with glTF exporting, so this is not an issue with this addon. Closing issue and opening one on the official glTF IO page.
