### ISSUE TITLE
Bug report: Can't bind clothes to armature/character through the "data transfer" modifier.

### ISSUE THREAD

**Issue by qwebeb5353** [saturday06/VRM-Addon-for-Blender#261]
## Describe the bug

After the addon update, I can't bind clothes to armature/character through the "date transfer" modifier. 

## To Reproduce

https://youtu.be/G066sdTp6xk
I used this guide.

https://youtu.be/8n4izA3BEcY what i try to do
You click on the mesh, hold down shift and left click on the armature, ctrl + p, with empty groups.
After that, you apply the data transfer modifier to the object that should have been attached to the model, select body in the source, check the checkbox for vertex data and vertex groups. After that the modifier apply.
After that, in pose mode in blender, the attached object/clothes should have followed the meshes, but now it does not work that way.

## Expected behavior

As you can see from the clip, in pose mode, the object I attached does not move with the bone and the whole arm. In older versions of the addon it worked. I've tried other guides, but they don't work now. And this way was the most convenient and easy.  

## Desktop (please complete the following information)

- OS: [win 10]
- Blender [3.4.1]
- Addon Version [(Version 2.16.4) June 24, 2023 UTC ]

## Additional context
This, of course, is probably not really a mistake, but I can't find now how I can fix it. If you know what I'm doing wrong please post or give me a link to a working guide on how to do this. Thanks

**Comment by qwebeb5353** [comment]
Oh, I noticed that it does move, but first of all without deformation. Somehow cursed they move. 
Second, the tethered objects only move when you rotate these through these bones:
J_Bip_R_Shoulder and left
head
neck
upperchest
chest
spine
hips
The rest of the bones, such as the legs and arms, don't move the anchored objects when I bind them via data transfer. That is, if I bind shoes to the character, they will not move when I move the leg bones. They will just fly forward when I start moving the spine backward.
https://youtu.be/sAo90Y3s_pg 

I'm frustrated. It seems to be exporting materials normally now, but the attachment of clothes to characters is broken. What should I do...

**Comment by qwebeb5353** [comment]
https://ibb.co/bQSp9ZF
Do I think I've found the reason?
Because the outliner is rendered now with this modifier, on the body, I can't easily and quickly bind clothes. 
If you apply it, the body disappears, and if you remove it, the outliner(gray lines on the clavicles, for example) disappears. 
Maybe you should make it render as it was before, in old versions? I'm new to blender and have not yet figured out how to fix or bypass this.

**Comment by IvyStal** [comment]
I am currently experiencing the same issue as well. I'm a beginner in Blender and after many trials and errors, I had to revert back to Blender 3.0 (was on 3.5) and VRM Addon 2.5.1 (was on the latest 2.17.7) which immediately fixed my problems, but I'd like to use the newer versions if possible.

**Comment by tarsan-vr** [comment]
I met similar problem.
I delete the outline modifier, then I tempolaly  can work shrinkwrap modifier, but, the outline modifier came back when I toggled between Object mode and Edit mode, and shrinkwrap modifier cannot work.
I think the outline modifier come back is a mistake.

If you can make VRM file that no use outline, you can tempolaly solve it.
For example, so I export it from VRoid Studio after I set no use outline .
(I'm doing this and using Blender3.6.1 and VRM format 2.17.7)
![1](https://github.com/saturday06/VRM-Addon-for-Blender/assets/1610003/fc9e210f-c3a0-4c65-893c-cda35452d2a2)

But unfortunatelly, the following did not work.
Deleting the outline modifier in only Blender(not use VRoid Studio), exporting it in vrm and reloading it didn't work.


And another tempolaly solve, turn off VRM addon during your manupilate. By doing this, the outline modifier will not come back and you can use modifiers.

**Comment by tarsan-vr** [comment]
Add information.

By turning off the outline generation mode of the material, you can turn off the automatic generation of the outline modifier.

At present, it seems that it is not possible to achieve both appearance and editing.
![1](https://github.com/saturday06/VRM-Addon-for-Blender/assets/1610003/13be43e8-0b66-4016-8587-a57af8ce2ef8)

**Comment by saturday06** [comment]
Thanks for reporting!
This bug has been fixed in the latest addon released now. Please try it.
https://github.com/saturday06/VRM-Addon-for-Blender/releases/tag/2_19_0

**Comment by tarsan-vr** [comment]
Thanks fixing.
I try 2.19.0 and I confirm  shrinkwrap modifier is worked.
I am happy with this result.

However, when I imported the VRoid Studio file,
I would like to inform you that the following phenomenon occurs.
Status: VRoid Studio 1.22.1(newest) choose Export format is VRM0.0
Blender 3.6.1

・Extra meshes are created
・Outline is not drawn
![スクリーンショット 2023-08-21 150231](https://github.com/saturday06/VRM-Addon-for-Blender/assets/1610003/7e4341de-ff65-4231-bdf3-036ba49892fe)

I don't care about this because I think it's obvious when other users import it so it can be deleted quickly and I'm not looking for accuracy in my outline drawing.
I just posted it for the benefit of others.

**Comment by saturday06** [comment]
Thanks for the additional report. However, my research was stopped because I am not experiencing the same phenomenon.

Please give me additional information to fix the bug.

When the bug occurs, You will see the error message in the "System Console." Please open the system console by pressing "Window" → "Toggle System Console" in the menu and post the contents of the system console.

<img width="1252" alt="スクリーンショット" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/a64f11bc-5a58-45c1-8991-2dd7924205d4">

My Environment:
- Windows 11
- VRoid Studio 1.22.1
- Blender 3.6.1
- VRM Add-on 2.19.0

My testing video.



https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/2563205e-7a84-4109-90e0-6273330436ca

**Comment by tarsan-vr** [comment]
Sorry, I tryed again same vrm file and same order, I couldn't same phenomenon.
I couldn't get any problem message in system console.
(just the following)

```
Read prefs: "C:\Users\yumiy\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Data are loaded, start creating Blender stuff
glTF import finished in 0.23s
```

All this fixes are reflected without problems.
(No extra meshes, outlines are visible, modifiers work)
It didn't occur, so it's no longer relevant, but my PC is Windows 10.


I'll contact you when it happens again. Anyway, thx for your great jobs.

**Comment by saturday06** [comment]
Thanks for the quick confirmation. I also see no problem with the message you wrote.

Perhaps the bug was only occurred at the time of the add-on update. I will continue to investigate.

Thank you for your patience with me!
