### ISSUE TITLE
Invalid Syntax error

### ISSUE THREAD

**Issue by Cloudy479** [saturday06/VRM-Addon-for-Blender#54]
<img width="809" alt="Screen Shot 2021-02-28 at 9 39 48 PM" src="https://user-images.githubusercontent.com/46914290/109456538-e7f9bf80-7a0d-11eb-8224-b2bbcdb14457.png">

I don't know if I'm just stupid, but everytime i try to add in this extension it gives me this error when I attempt to check the plugin box

**Comment by Cj-bc** [comment]
First of all, this addon is for blender 2.82+ so that I think your blender version(2.79) isn't supported officially.
It's better to upgrade blender to 2.82+ if you can.
if you really want to use with 2.79, there's [older version](https://github.com/iCyP/VRM_IMPORTER_for_Blender2_79) but please remember it's **no longer maintained**



---

Talking about the error message, it is because of Python version.
I'm not sure about this, but 2.79 seems using older than 3.5., which doesn't support [typing](https://docs.python.org/3/library/typing.html) feature introduced at Python 3.5.
