### ISSUE TITLE
TypeError VV

### ISSUE THREAD

**Issue by gamemaster7720** [saturday06/VRM-Addon-for-Blender#7]
so i tried to export my mode and it keeps saying this and idk what to do any fixes ?
![issues](https://user-images.githubusercontent.com/40168481/77910460-7100f780-728f-11ea-9a06-ee1dc08f804e.png)

**Comment by iCyP** [comment]
Please use  as below.
 - select an armature and meshes for export.
 - **from blender default export menu(topbar->File->Export->.vrm).**
    - This addon doesn't provide export button.
 - with blender that official release (2.82a on steam)
 - with latest addon (current : 8add672) 

And...

I won't support IO function call from other addon. 
(I thought from your background of screenshot, you try to export from button of another addon.) 

Thanks.

**Comment by gamemaster7720** [comment]
im trying to export it but i get this the whole time 
![image](https://user-images.githubusercontent.com/40168481/77929540-11fcac00-72aa-11ea-8a73-2d9fa437ce40.png)

**Comment by iCyP** [comment]
I tried to import-export Vroid model from Blender2.80, latest addon and file export menu, And it's success, the issue is not reproduction.
Then, you are only person who are able to find what is caused it. 
I cannot have solution about it. Sorry for inconvenience. 

And,
1. If you using Python of not bundled in official Blender, please try with it.
2. Try to use https://github.com/iCyP/VRM_IMPORTER_for_Blender2_8/releases/tag/0.78b
    1. remove addon.
    2. decompless above soucecode zip.
    3. rename folder that exclude hyphen(-).
    4. move folder into addons folder.
    5. enable from blender setting window.

Many thanks.

**Comment by iCyP** [comment]
This addon is No longer support because I cannot trust VRM-C.
