### ISSUE TITLE
Bug report / バグ報告: Textures are exporting without materials

### ISSUE THREAD

**Issue by CommonStarguy** [saturday06/VRM-Addon-for-Blender#99]
**Describe the bug / バグについて**
どのようなバグが起きているのか書いてください。
>When exporting VRM from Blender, no texture materials are able to be baked or saved with the model.

**To Reproduce / バグの再現方法**
1. Create model/armature
2. Click on 'File > Export > VRM (.vrm)'
3. Import to VSeeFace
バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

**Expected behavior / 期待する動作**
どうのようにバグを直してほしいか書いてください。
>Model should have textures/shader

**Screenshots / スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
>How model looks in viewport:
![image](https://user-images.githubusercontent.com/83615968/159157633-3ceb898d-b0f4-4184-894c-e4be8201cc38.png)
>How model looks in VSeeFace (SpringBones also need adjusting)
![image](https://user-images.githubusercontent.com/83615968/159157679-0f6c151c-aa25-4d71-9d17-f0f0dbf79df1.png)

**Desktop (please complete the following information) / PC環境情報**
- OS: Windows 10
- Blender 3.0.1
- Addon Version 2.2.0

**Additional context / なにか他に書いておきたいことはこちらへ**

**Comment by saturday06** [comment]
Thanks for reporting!

The add-on exports materials in the same way as the Blender glTF 2.0 Add-on because VRM is derived from glTF 2.0. glTF 2.0 Add-on is limited in the number of supported shader node groups, see documentation.
https://docs.blender.org/manual/en/3.0/addons/import_export/scene_gltf2.html?highlight=gltf#exported-materials

In addition, our add-on adds VRM's own shader node group. Materials are exported using them.
![スクリーンショット 2022-03-20 20 30 22](https://user-images.githubusercontent.com/532872/159160104-c7c26e97-8edc-4726-ab9a-a1fda4dbce9b.png)

This is a common pitfall and will be documented in a future document.

**Comment by saturday06** [comment]
Documentation written
https://vrm-addon-for-blender.info/en/material-pbr
